### ISSUE TITLE
Expose socket instance state

### ISSUE THREAD

**Issue by mdarens** [civicsource/react-socket-hooks#2]
`useSocket` should return the underlying socket's `readyState`, the handlers for send, open and close events, and, for convenience, boolean `isConnecting`, `isOpen`, `isClosing`, `isClosed`, so components consuming the hook can display socket status & _hook_ into changes in the socket state for side effects.

**Comment by chadly** [comment]
I implemented returning the socket `readyState` but I disagree on exposing the imperative APIs. Unless we have a good reason to, I'd rather keep the public API of the hook declarative.

**Comment by chadly** [comment]
Also, the flags seem redundant to me. I'd rather keep the API surface area as small as possible.
